hyperparameters:
  learning_rate: 0.001
  num_epochs: 50
  batch_size: 16
  patience: 5
  min_delta: 0.001
  image_height: 256
  image_width: 256

paths:
  train_input_dir: "./synthetic_data/train/noisy_images"
  train_target_dir: "./synthetic_data/train/clean_images"
  val_input_dir: "./synthetic_data/val/noisy_images"
  val_target_dir: "./synthetic_data/val/clean_images"
  test_input_dir: "./synthetic_data/test/noisy_images"
  test_target_dir: "./synthetic_data/test/clean_images"
  plot_dir: "./outputs/plots"
  output_image_dir: "./outputs/images"
  checkpoint_dir: "./outputs/checkpoints"